# This loads nvm
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# Custom
alias vim='nvim'
source $HOME/.local/bin/wezterm.sh
source /etc/zsh_command_not_found
export PATH=$HOME/.local/bin:$PATH
export HOSTNAME=$HOST
export skip_global_compinit=1
